---
title: "assignment_2 exhibits"
output:   
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
date: "2022-11-25"
---

```{r include=FALSE, message=FALSE, warning=FALSE}
rm(list=ls())
# load libraries
library(tidyverse)
library(haven)
library(data.table)
library(rms)
library(lspline)
library(huxtable)
library(modelsummary)
library(pscl)
library(esquisse)
library(ggplot2)
library(mfx)
library(scales)
```

```{r echo=TRUE, include=FALSE}
# load data (both hotel price and feature)
hotels_p <- read_csv('https://osf.io/p6tyr/download')
hotels_f <- read_csv('https://osf.io/utwjs/download')
```

```{r, include=FALSE}
# joining the 2 tables
df <- left_join(hotels_f, hotels_p, by = "hotel_id")
rm(hotels_f, hotels_p)
```

```{r, include=FALSE}
# select Paris,filter "hotel"
df <- df %>% filter(city_actual == "Seville")

df <- df[df$accommodation_type == "Hotel",]

# filtering extreme values (I am only interested in hotels which are 600 or cheaper)
df <- df %>% filter(!is.na(hotel_id)) %>% 
  filter(price <= 600) %>% 
  filter(!is.na(stars)) %>% 
  filter(!is.na(distance)) %>% 
  filter(!is.na(rating))

# creating binary variable for high_rated
df$high_rated <- ifelse(df$rating >= 4, 1, 0)

# creating log price column
df$lnprice <- log(df$price)
```

# data summary
```{r, echo=FALSE}
# data summary on highly rated & stars
p95 <- function(x){ quantile(x, .95, na.rm = TRUE)}
data_sum <- datasummary( high_rated + distance + stars ~ 
                           mean + SD + min + max + median + p95 + N, 
                         data = df , title = "Data Summary" )
data_sum
```

# Plots for distance/stars vs probability of being high rated
```{r, echo=FALSE, warning=FALSE, fig.height=4, fig.width=4}
# checking the regression line (loess) for each variable

# by distance
g1 <- ggplot(data = df, aes(x = distance, y = high_rated)) +
  geom_smooth(method = "loess", formula = y~x, color = "dodgerblue2") +
  scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2), labels = scales::percent) +
  labs(x = "Distance",y = "Probability to be high rated") +
  theme_bw() +
  ggtitle("Figure 1 : Probability of being high rated vs Distance") +
   theme(plot.title = element_text(size = 10))
g1

# star
g2 <- ggplot(data = df, aes(x = stars, y = high_rated)) +
  geom_smooth(method = "loess", formula = y~x, color = "sienna1") +
  scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2), labels = scales::percent) +
  labs(x = "Stars",y = "Probability to be high rated") +
  theme_bw() +
  ggtitle("Figure 2 : Probability of being high rated vs Stars")+
   theme(plot.title = element_text(size = 10))

g2
```

```{r, include = FALSE}
# Save lists for Regression Model Summary table
# creating the LPM with binary variable (high_rated)
lpm <- lm(high_rated ~ lspline(stars, c(4)) + lspline(distance, c(0.6, 1.6)) + lnprice, data = df)
df$pred_lpm <- predict(lpm)

summary(df$pred_lpm)


# the maximum probability is observed to be larger than 1, we should take logit and probit to predict the values for the data
```
# we used logit regression because it restrict the probability values between zero and 1 (include in documentation)
```{r, include=FALSE} 
# logit coefficients
logit <- glm(high_rated ~ lspline(stars, c(4)) + lspline(distance,c(0.6, 1.6))+ lnprice, data=df, family='binomial'(link = "logit"))

# add predicted probabilities into df
df$pred_logit <- predict.glm(logit, type="response")

# check maximum probability if it is == 1
summary(df$pred_logit)

# logit marginal differences
logit_marg <- logitmfx(formula = high_rated ~ lspline(stars, c(4)) + lspline(distance,c(0.6, 1.6)) + lnprice, data=df, atmean=FALSE)

# probit coefficients
probit <- glm(high_rated ~ lspline(stars, c(4)) + lspline(distance,c(0.6, 1.6))+ lnprice, data=df, family=binomial(link="probit"))

# add predicted probabilities into df
df$pred_probit <- predict.glm(probit, type="response")

# check maximum probability if it is == 1
summary(df$pred_probit)

# probit marginal differences
probit_marg <- probitmfx(formula = high_rated ~ lspline(stars, c(4)) + lspline(distance,c(0.6, 1.6))+ lnprice, data=df, atmean=F)
```

# Regression Model Summary
```{r echo=FALSE, message=FALSE, warning=FALSE}
rename <- c('(Intercept)' = 'Constant',
        'lspline(stars, c(4))1' = '4 stars of lower',
        'lspline(stars, c(4))2' = 'higher than 4 stars',
        'lspline(distance, c(0.6, 1.6))1' = 'disatnce >= 0.6',
        'lspline(distance, c(0.6, 1.6))2' = 'disatnce >0.6, <=1.6',
        'lspline(distance, c(0.6, 1.6))3' = 'disatnce >1.6')
summary <- msummary(list("1. LPM" = lpm, "2. logit coeffs" = logit, "3. logit marg" = logit_marg, "4. probit" = probit, "5. probit marg" = probit_marg),
         fmt="%.3f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC|R2|PseudoR2',
         stars=c('*' = .05, '**' = .01),
          coef_rename = rename,
         title = "Regression Model Summary of Hotels in Seville")
summary
```

# Predicted Probability of LPM, Logit and Probit Models
```{r, echo=FALSE, warning=FALSE, fig.height=4, fig.width=6}
g3 <- ggplot(data = df) +
  geom_point(aes(x=pred_lpm, y=pred_probit, color="Probit"), size=0.5,  shape=16) +
  geom_point(aes(x=pred_lpm, y=pred_logit,  color="Logit"), size=0.5,  shape=16) +
  geom_line(aes(x=pred_lpm, y=pred_lpm,    color="45 Degree line"), size=0.5) +
  labs(x = "Predicted probability of being high rated (LPM)", y="Predicted probability")+
  scale_y_continuous(expand = c(0.00,0.0), limits = c(0,1), breaks = seq(0,1,0.2)) +
  scale_x_continuous(expand = c(0.00,0.0), limits = c(0,1), breaks = seq(0,1,0.2)) +
  scale_color_manual(name = "", values=c("#541352FF", "#3a5e8cFF","#10a53dFF")) +
  theme_light()+
  ggtitle("Figure 3 : Predicted Probability of LPM, Logit and Probit Models")
  
g3
```





